-- E-Commerce Sales Analysis
-- Project 1 | MySQL + Power BI
-- Database: ecommerce_analytics

USE ecommerce_analytics;

-- Q1. What is the total revenue?
SELECT
    SUM(o.quantity * p.price * (1 - o.discount)) AS total_revenue
FROM orders o
INNER JOIN products p
    ON o.product_id = p.product_id;

-- Q2. How many total orders were placed?
SELECT
    COUNT(DISTINCT order_id) AS total_orders
FROM orders;

-- Q3. How many unique customers placed orders?
SELECT
    COUNT(DISTINCT customer_id) AS total_customers
FROM orders;

-- Q4. What is the Average Order Value (AOV)?
SELECT
    SUM(o.quantity * p.price * (1 - o.discount))
    / COUNT(DISTINCT o.order_id) AS average_order_value
FROM orders o
INNER JOIN products p
    ON o.product_id = p.product_id;

-- Q5. What is the revenue generated by each category?
SELECT
    p.category,
    SUM(o.quantity * p.price * (1 - o.discount)) AS total_revenue
FROM orders o
INNER JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Q6. Which products generate the highest revenue?
SELECT
    p.product_id,
    p.product_name,
    SUM(o.quantity * p.price * (1 - o.discount)) AS total_revenue
FROM orders o
INNER JOIN products p
    ON o.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC;

-- Q7. How many orders does each customer place?
SELECT
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC;

-- Q8. What is the average number of orders per customer?
SELECT
    AVG(customer_orders) AS average_orders_per_customer
FROM (
    SELECT
        customer_id,
        COUNT(order_id) AS customer_orders
    FROM orders
    GROUP BY customer_id
) AS customer_order_summary;

-- Q9. What percentage of customers are repeat customers?
SELECT
    ROUND(
        100.0 * SUM(CASE WHEN total_orders > 1 THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS repeat_customer_rate
FROM (
    SELECT
        customer_id,
        COUNT(order_id) AS total_orders
    FROM orders
    GROUP BY customer_id
) AS customer_orders;

-- Q10. What is the revenue generated by each state?
SELECT
    c.state,
    SUM(o.quantity * p.price * (1 - o.discount)) AS total_revenue
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id
INNER JOIN products p
    ON o.product_id = p.product_id
GROUP BY c.state
ORDER BY total_revenue DESC;

-- Q11. How does revenue change month by month?
SELECT
    DATE_FORMAT(o.order_date, '%Y-%m') AS order_month,
    SUM(o.quantity * p.price * (1 - o.discount)) AS total_revenue
FROM orders o
INNER JOIN products p
    ON o.product_id = p.product_id
GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
ORDER BY order_month;

-- Q12. Who are the top 10 customers by revenue?
SELECT
    c.customer_id,
    c.customer_name,
    SUM(o.quantity * p.price * (1 - o.discount)) AS total_revenue
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id
INNER JOIN products p
    ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_revenue DESC
LIMIT 10;

-- Q13. What is each customer's contribution to total revenue?
SELECT
    c.customer_id,
    c.customer_name,
    SUM(o.quantity * p.price * (1 - o.discount)) AS customer_revenue,
    ROUND(
        100.0 * SUM(o.quantity * p.price * (1 - o.discount))
        / (
            SELECT
                SUM(o2.quantity * p2.price * (1 - o2.discount))
            FROM orders o2
            INNER JOIN products p2
                ON o2.product_id = p2.product_id
        ),
        2
    ) AS revenue_contribution_pct
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id
INNER JOIN products p
    ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
ORDER BY customer_revenue DESC;
